[template.environment]
  CONTENTFUL_SPACE_ID = "Set this to you Contentful space ID"
  CONTENTFUL_ACCESS_TOKEN = "Set this to your Contentful access token"


[[redirects]]
/blog /https://netlify.com 200
