[template.environment]
  CONTENTFUL_SPACE_ID = "Set this to you Contentful space ID"
  CONTENTFUL_ACCESS_TOKEN = "Set this to your Contentful access token"


[[plugins]]
package = "./plugins/netlify-purge-cloudflare-on-deploy"
